# Tipos de objetos
En R existen varios tipos de objectos que permiten que el usuario pueda almacenar la información para realizar procedimientos estadísticos y gráficos. Los principales objetos en R son vectores, matrices, arreglos, marcos de datos y listas. A continuación se presentan las características de estos objetos y la forma para crearlos.
## 2.1 Vectores 
Los vectores vectores son arreglos ordenados en los cuales se puede almacenar información de tipo numérico (variable cuantitativa), alfanumérico (variable cualitativa) o lógico (TRUE o FALSE), pero no mezclas de éstos. La función de R para crear un vector es c() y que significa concatenar; dentro de los paréntesis de esta función se ubica la información a almacenar. Una vez construído el vector se acostumbra a etiquetarlo con un nombre corto y representativo de la información que almacena, la asignación se hace por medio del operador <- entre el nombre y el vector.

A continuación se presenta un ejemplo de cómo crear tres vectores que contienen las respuestas de cinco personas a tres preguntas que se les realizaron.

In [1]:
edad = c(15, 19, 13, NA, 20)
deporte = c(TRUE, TRUE, NA, FALSE, TRUE)
comic.fav = c(NA, 'Superman', 'Batman', NA, 'Batman')

In [2]:
edad

[1] 15 19 13 NA 20

### 2.1.1 ¿Cómo extraer elementos de un vector?
Para extraer un elemento almacenado dentro un vector se usan los corchetes [] y dentro de ellos la posición o posiciones que interesan.

In [4]:
edad[3]

[1] 13

## 2.2 Matrices

Las matrices son arreglos rectangulares de filas y columnas con información numérica, alfanumérica o lógica. Para construir una matriz se usa la función matrix( ). Por ejemplo, para crear una matriz de 4 filas y 5 columnas (de dimensión 4×5
) con los primeros 20 números positivos se escribe el código siguiente en la consola.

In [5]:
mimatriz = matrix(data=1:20, nrow=4, ncol=5, byrow=FALSE)

In [6]:
mimatriz

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

### 2.2.1 ¿Cómo extraer elementos de una matriz?

Al igual que en el caso de los vectores, para extraer elementos almacenados dentro de una matriz se usan los corchetes [ , ] y dentro, separado por una coma, el número de fila(s) y el número de columna(s) que nos interesan.


In [11]:
mimatriz[3, 4]
mimatriz[2, ]
mimatriz[, 5]
mimatriz[, -c(2, 4)]

[1] 15

[1]  2  6 10 14 18

[1] 17 18 19 20

[,1] [,2] [,3]
[1,] 1     9   17  
[2,] 2    10   18  
[3,] 3    11   19  
[4,] 4    12   20

## 2.3 Arreglos 
Un arreglo es una matriz de varias dimensiones con información numérica, alfanumérica o lógica. Para construir una arreglo se usa la función array( ). Por ejemplo, para crear un arreglo de 3×4×2 con las primeras 24 letras minúsculas del alfabeto se escribe el siguiente código.


In [15]:
miarray <- array(data=letters[1:24], dim=c(3, 4, 2))
miarray
miarray[1, 3, 2]

, , 1

     [,1] [,2] [,3] [,4]
[1,] "a"  "d"  "g"  "j" 
[2,] "b"  "e"  "h"  "k" 
[3,] "c"  "f"  "i"  "l" 

, , 2

     [,1] [,2] [,3] [,4]
[1,] "m"  "p"  "s"  "v" 
[2,] "n"  "q"  "t"  "w" 
[3,] "o"  "r"  "u"  "x"

[1] "s"

## 2.4 Marco de datos (DataFrame
El marco de datos marco de datos o data frame es uno de los objetos más utilizados porque permite agrupar vectores con información de diferente tipo (numérica, alfanumérica o lógica) en un mismo objeto, la única restricción es que los vectores deben tener la misma longitud. Para crear un marco de datos se usa la función data.frame( ), como ejemplo vamos a crear un marco de datos con los vectores edad, deporte y comic.fav definidos anteriormente.

In [23]:
mimarco <- data.frame(edad, deporte, comic.fav)
mimarco
mimarco$deporte
mimarco[, 2]
mimarco[["deporte"]]
mimarco[c("deporte", "edad")]
mimarco[2:4, 1]

edad deporte comic.fav
1 15    TRUE   NA       
2 19    TRUE   Superman 
3 13      NA   Batman   
4 NA   FALSE   NA       
5 20    TRUE   Batman

[1]  TRUE  TRUE    NA FALSE  TRUE

[1]  TRUE  TRUE    NA FALSE  TRUE

[1]  TRUE  TRUE    NA FALSE  TRUE

deporte edad
1  TRUE   15  
2  TRUE   19  
3    NA   13  
4 FALSE   NA  
5  TRUE   20

[1] 19 13 NA

## 2.4.2 ¿Cómo extraer subconjuntos de un marco de datos? 
Para extraer partes de un marco de datos se puede utilizar la función subset(x, subset, select). El parámetro x sirve para indicar el marco de datos original, el parámetro subset sirve para colocar la condición y el parámetro select sirve para quedarnos sólo con algunas de las variables del marco de datos. A continuación varios ejemplos de la función subset para ver su utilidad.

In [26]:
subset(mimarco, subset=deporte == TRUE)
subset(mimarco, subset=edad >= 17)
subset(mimarco, subset=edad < 20, select=c('deporte', 'comic.fav'))

edad deporte comic.fav
1 15   TRUE    NA       
2 19   TRUE    Superman 
5 20   TRUE    Batman

edad deporte comic.fav
2 19   TRUE    Superman 
5 20   TRUE    Batman

deporte comic.fav
1 TRUE    NA       
2 TRUE    Superman 
3   NA    Batman

Leer la base de datos medidas del cuerpo disponible en este enlace https://raw.githubusercontent.com/fhernanb/datos/master/medidas_cuerpo. Extraer de esta base de datos una sub-base o subconjunto que contenga sólo la edad, peso, altura y sexo de aquellos que miden más de 185 cm y pesan más de 8

In [28]:
url = 'https://raw.githubusercontent.com/fhernanb/datos/master/medidas_cuerpo'
dt1 = read.table(url, header=T)
dim(dt1)  # Para conocer la dimensión de la base original
dt2 = subset(x=dt1, subset=altura > 185 & peso > 80,
              select=c('sexo', 'edad', 'peso', 'altura'))
dt2  # Para mostrar la base de datos final

[1] 36  6

sexo   edad peso altura
1  Hombre 43   87.3 188.0 
6  Hombre 33   85.9 188.0 
15 Hombre 30   98.2 190.5

## 2.5 Listas 
Las listas son otro tipo de objeto muy usado para almacenar objetos de diferente tipo. La instrucción para crear una lista es list( ). A continuación vamos a crear una lista que contiene tres objetos: un vector con 5 números aleatorios llamado mivector, una matriz de dimensión 6×2 con los primeros doce números enteros positivos llamada matriz2 y el tercer objeto será el marco de datos mimarco creado en el apartado anterior. Las instrucciones para crear la lista requerida se muestran a continuación.

In [29]:
set.seed(12345)
mivector <- runif(n=5)
matriz2 <- matrix(data=1:12, ncol=6)
milista <- list(E1=mivector, E2=matriz2, E3=mimarco)

La función set.seed de la línea número 1 sirve para fijar la semilla de tal manera que los números aleatorios generados en la segunda línea con la función runif sean siempre los mismos. En la última línea del código anterior se construye la lista, dentro de la función list se colocan los tres objetos mivector, matriz2 y mimarco. Es posible colocarle un nombre especial a cada uno de los elementos de la lista, en este ejemplo se colocaron los nombres E1, E2 y E3 para cada uno de los tres elementos. Para observar lo que quedó almacenado en la lista se escribe milista en la consola y el resultado se muestra a continuación.

In [31]:
milista
milista$E2
milista[[2]]
class(milista$E2)

$E1
[1] 0.7209039 0.8757732 0.7609823 0.8861246 0.4564810

$E2
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    3    5    7    9   11
[2,]    2    4    6    8   10   12

$E3
  edad deporte comic.fav
1   15    TRUE      <NA>
2   19    TRUE  Superman
3   13      NA    Batman
4   NA   FALSE      <NA>
5   20    TRUE    Batman

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    3    5    7     9   11  
[2,] 2    4    6    8    10   12

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    3    5    7     9   11  
[2,] 2    4    6    8    10   12

[1] "matrix" "array"

# Ejercicios
Use funciones o procedimientos (varias líneas) de R para responder cada una de las siguientes preguntas.

1. Construya un vector con la primeras 20 letras MAYÚSCULAS usando la función LETTERS.

2. Construya una matriz de 10×10 con los primeros 100 números positivos pares.

3. Construya una matriz identidad de dimension 3×3. Recuerde que una matriz identidad tiene sólo unos en la diagonal principal y los demás elementos son cero.

4. Construya una lista con los anteriores tres objetos creados.

5. Construya un marco de datos o data frame con las respuestas de 3 personas a las preguntas: (a) ¿Cuál es su edad en años? (b) ¿Tipo de música que más le gusta? (c) ¿Tiene usted pareja sentimental estable?

6. ¿Cuál es el error al correr el siguiente código? ¿A qué se debe?
        edad <- c(15, 19, 13, NA, 20)
        deporte <- c(TRUE, TRUE, NA, FALSE, TRUE)
        comic.fav <- c(NA, 'Superman', 'Batman', NA, 'Batman')
        matrix(edad, deporte, comic.fav)

In [38]:
letters_vector = c(LETTERS[1:20])

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T"

In [63]:
odd_matrix = matrix(data=seq(from=2, to=100, by=2), nrow=10, ncol=10, byrow=TRUE)

In [66]:
ident_matrix = diag(3)

In [67]:
milista = list(E1=letters_vector, E2=odd_matrix, E3=ident_matrix)

In [3]:
df = data.frame(edad=c(20,25,30), gusto_musical=c('Rock', 'Jazz', 'Country'), esta_casado=c('si','no', 'si'))
df

edad gusto_musical esta_casado
1 20   Rock          si         
2 25   Jazz          no         
3 30   Country       si

In [5]:
edad <- c(15, 19, 13, NA, 20)
deporte <- c(TRUE, TRUE, NA, FALSE, TRUE)
comic.fav <- c(NA, 'Superman', 'Batman', NA, 'Batman')
data.frame(edad, deporte, comic.fav)

edad deporte comic.fav
1 15    TRUE   NA       
2 19    TRUE   Superman 
3 13      NA   Batman   
4 NA   FALSE   NA       
5 20    TRUE   Batman